import { aggressiveTokenizerFr } from "./aggressiveTokenizerFr";

const text = `Affectueusement surnommé « Gabo » dans toute l'Amérique latine, le Colombien Gabriel Garcia Marquez, prix Nobel de littérature 1982, l'un des plus grands écrivains du XXe siècle, est mort À son domicile de Mexico jeudi 17 avril. Il était âgé de 87 ans. Son Œuvre a été traduite dans toutes les langues ou presque, et vendue à quelque 50 millions d'exemplaires.`;

const tokenized = [
  "Affectueusement",
  "surnommé",
  "Gabo",
  "dans",
  "toute",
  "l",
  "Amérique",
  "latine",
  "le",
  "Colombien",
  "Gabriel",
  "Garcia",
  "Marquez",
  "prix",
  "Nobel",
  "de",
  "littérature",
  "1982",
  "l",
  "un",
  "des",
  "plus",
  "grands",
  "écrivains",
  "du",
  "XXe",
  "siècle",
  "est",
  "mort",
  "À",
  "son",
  "domicile",
  "de",
  "Mexico",
  "jeudi",
  "17",
  "avril",
  "Il",
  "était",
  "âgé",
  "de",
  "87",
  "ans",
  "Son",
  "Œuvre",
  "a",
  "été",
  "traduite",
  "dans",
  "toutes",
  "les",
  "langues",
  "ou",
  "presque",
  "et",
  "vendue",
  "à",
  "quelque",
  "50",
  "millions",
  "d",
  "exemplaires"
];

describe("Aggressive tokenizer", () => {
  test("should tokenize strings", function() {
    expect(aggressiveTokenizerFr(text)).toEqual(tokenized);
  });
});
